version: '3'
services:
  backend-container:
    build:
      context: ./Backend
    ports:
      - "9000:443"
    volumes:
      - ${PWD}/Database:/kds-backend/Database
    container_name: backend-container

  frontend-container:
    depends_on:
      - backend-container
    build:
      context: ./Frontend
    ports:
      - "8080:80"
      - "8000:443"
    container_name: frontend-container

  prometheus:
    depends_on:
      - backend-container
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Mount your Prometheus config
    container_name: prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    container_name: grafana
