version: '3'
services:
  kds-backend-container:
    build:
      context: ./Backend
    ports:
      - "9000:443"
    volumes:
      - ${PWD}/Database:/kds-backend/Database
    container_name: kds-backend-container

  kds-frontend-container:
    depends_on:
      - kds-backend-container
    build:
      context: ./Frontend
    ports:
      - "8080:80"
      - "8000:443"
    container_name: kds-frontend-container
